version: "1"
services:
  openmeeting:
    image: apache/openmeetings:7.2.0
    ports: 
      - 5443:5443
    volumes:
      - /home/user/project/:/opt/omdata
    networks:
      my_macvlan:
          ipv4_address: 192.168.0.2
networks:
  my_macvlan:
    driver: macvlan
    driver_opts:
      parent: enp0s3
    ipam:
      config:
        - subnet: "192.168.0.1/24"
          gateway: "192.168.0.1"
